solution: CyLR.sln
matrix:
  include:
    - os: linux
      dist: bionic
      language: csharp
      mono: none
      dotnet: 3.1.302
    - os: osx
      language: csharp
      mono: none
      dotnet: 3.1.302
    - os: windows
      language: csharp
      mono: none
      dotnet: none

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y clang-3.9 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install dotnetcore-sdk 7zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then BUILD_ARCH=linux-x64 USE_CORERT=TRUE scripts/test.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then BUILD_ARCH=linux-x64 USE_CORERT=TRUE scripts/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then BUILD_ARCH=linux-x64 USE_CORERT=TRUE scripts/package.sh ; fi

  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/test_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/build_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/package_win.ps1 ; fi

  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then BUILD_ARCH=osx-x64 USE_CORERT=TRUE scripts/test.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then BUILD_ARCH=osx-x64 USE_CORERT=TRUE scripts/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then BUILD_ARCH=osx-x64 USE_CORERT=TRUE scripts/package.sh ; fi

deploy:
  provider: releases
  api_key:
    secure: M5ZAU+BBp5rFFKrTWG2FmC325jOxbNVgjf3U76Wu8AtndmPfvpHQLf8EL54xTrbCWkRRwW8HxpSw9LJp2nMnwbD58sNzWpw5XnjG5j9tQf05y/8vKhPSnUVVaOFmSzitg/kJrkyb3wC14inDMdRfk2OtwEjTjjWQUEFcdCuYLodzHu52tJCrivtKQpqUMQZtb3xJg45f0LHrTxS420HXHR0xb397HLr/uIvh1139g2ltmC8/ifiObGQTwKcdI3ZeOXfkznRRbZj+fz1JrhjlK/qDlo20QVmqXLOJrNwIYEYtIWyLF7Fa+88qSQfp8ZrjscVtmUsgWholLucQc28LKU90ycslvEAB70LjZlhNW2zYLJwwLpGnXiHLmVCV+50XNNT1THXwMIJOcOFbgkRK2Cx0VB3eHbbRS+F4jaye8FI41syFIACku/WqSvD3iG5JCX44UMxahQRjf+mpSvU3DONYsYJnZXhQLZjlL4qz1RHS/sslnOYtPbR4l6Jf2bZepOiGs+egNvTV7NgYMz3M730TPEh9t6duk+nx1CwOeRVwoCe5mI4ZEn//Sh5ODSwx2gevecLAfw8xfZjgW1HOzfbxAu2WOKdw8sOZGEEtsaM7HoOZgwRhmbubw2+ypk+XOm/HtF6j2tCLGz+sjlMIpfwuZsTONnabFFg+XfX7BK0=
  file_glob: true
  file: archive/**/*
  name: Draft Release
  draft: true
  skip_cleanup: true
  on:
    tags: true
